set -g history-limit 50000
set-window-option -g window-status-current-style bold,fg=brightyellow,bg=red
set-window-option -g window-status-current-format "#{window_index}:#{window_name}"
set-window-option -g window-status-format "#{window_index}:#{window_name}"

set-option -gs default-terminal "xterm-256color"
# Better color support.
set-option -gas terminal-overrides "*:Tc"
set-option -gas terminal-overrides "*:RGB"
# Enable double/curly underline.
set-option -gas terminal-overrides '*:Smulx=\E[4::%p1%dm'
set-option -gas terminal-overrides '*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'
